default['redis']['version'] = '2.6.11-1'
default['redis']['user'] = 'redis'
default['redis']['group'] = 'redis'
default['redis']['path'] = '/usr/bin'
default['redis']['pidfile'] = '/var/run/redis/redis.pid'
default['redis']['conf'] = '/etc/redis/redis.conf'
default['redis']['port'] = '6379'
